name: tiamat_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-image=0.24.0
  - opencv=4.10.0
  - pillow=11.0.0
  - tqdm=4.67.0
  - cython
  
  - pip:
      - ultralytics==8.3.34
      - albumentations==1.4.18
      - pytorch
      - torchvision
